[package]
name = "oo7-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.12.0", features = [ "attributes" ] }
chrono = { version = "0.4.31", default-features = false, features = ["alloc", "clock"] }
clap = { version = "4.4.6", features = [ "cargo", "derive" ] }
oo7 = { path = "../client" }
rpassword = "7.2.0"
